### ISSUE TITLE
Support upgrade to Flutter 2

### ISSUE THREAD

**Issue by GiorgioBertolotti** [marcoesposito1988/http_auth#10]
Hello,
I recently upgraded to Flutter 2 and had a lot of pubspec errors caused by incompatibilities between packages, and one of these was about `http_auth`:

> Because uuid >=3.0.0 depends on crypto ^3.0.0 and http_auth 0.3.1 depends on crypto >=2.0.0 <2.2.0, uuid >=3.0.0 is incompatible with http_auth 0.3.1.

Would it be possible to upgrade the package dependencies to support the latest versions?
Thanks!

**Comment by marcoesposito1988** [comment]
Sure, I just released a new version 0.3.2. Please let me know if you still encounter any issues

**Comment by GiorgioBertolotti** [comment]
Works great, thanks! 🚀
