### ISSUE TITLE
Get request with DigestAuth return Unsupported Media Type 415

### ISSUE THREAD

**Issue by remythales** [marcoesposito1988/http_auth#14]
Hi, the authentication seems to works fine for me but constantly getting error 415 even if the header is correct.

 Map<String, String> headers = {
                "Content-Encoding": "gzip, deflate, br",
                "Content-Language": "en-US",
                "Content-Type": "text/plain; charset=UTF-8" //does not work
                /* "Content-Type": "text/plain;charset=ISO-8859-1"*/ //does not work 
              };
              var client = DigestAuthClient('apiUser', '6tX2aGIfTN9bXfKG');

`
              final url =
                  Uri.parse('http://localhost:8080/api/v1/owner/vouchers');
              var response = client
                  .get(url, headers: headers)
                  .then((value) => print(value.statusCode));`

the server (private) responds well with my curl command as firefox so it cannot be a server issue.
I am quite clueless here...

CURL:
` curl -D - --digest -u apiUser:6tX2aGIfTN9bXfKG --request GET "http://localhost:8080/api/v1/owner/vouchers" --header 'Content-Type: text/plain'`
-> Get 200

Firefox:
![image](https://user-images.githubusercontent.com/68057059/169487477-0e3e6f2f-ffba-4f2d-b053-f508dd3dc61e.png)
-> Get 200

Thanks for helping out if any ideas :)
Remy

**Comment by ABMamun-All** [comment]
r u really mad..!!!!!???

**Comment by marcoesposito1988** [comment]
Hi @remythales,

please ignore the previous uncivilized comment to your issue.  The author is not affiliated to the repository in any way.

If you found a solution to your issue, would you mind sharing it?

I am aware of compatibility issues with some servers, but they are very hard to pinpoint. I already compared my implementation to many others I could get access to and that seem not to have this problem, but I couldn't find any obvious difference in the algorithm nor in the output.

**Comment by remythales** [comment]
Hi, 
No problems. This was quite a long time ago, I do not recall the full solution to it, but I remember setting the header to a more permissive request.
Remy
