### ISSUE TITLE
Compatibility with the new http 1.0.0 package

### ISSUE THREAD

**Issue by wsaf2000** [marcoesposito1988/http_auth#16]
The new version of http package 1.0.0 conflicts with http_auth 1.0.1.
The http_auth 1.0.1 package depends on the version >=0.9.0 <1.0.0 of the http package.
If there is no effective incompatibility, I suggest updating this dependency.

**Comment by marcoesposito1988** [comment]
Good point, thanks for the heads up! 
Please ring a bell if version 1.0.2 doesn't fix the issue.

**Comment by wsaf2000** [comment]
Very good! I confirm that version 1.0.2 fixed the issue.
